// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Yami_8DIR","status":true,"description":"プレイヤーの8方向の移動が可能になります。","parameters":{}},
{"name":"Community_Basic","status":true,"description":"基本的なパラメーターを設定するプラグインです。","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"on"}},
{"name":"YED_Eventspassable","status":true,"description":"イベントもしくはフォロワーが他のイベントにヒットした際に、途中で停止してしまうことを防ぎます。","parameters":{}}
];
